### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/EverlastingGobStopper#13]
Could you confirm if the repo is still active and needed? To do so, just close this issue by end of Feb 2024. If not, we'll archive the repo. The repo can still be unarchived, so it's not a destructive action.

**Comment by ThiloVolprich** [comment]
Hey Paul,

I don’t think this is needed anymore. 
The request for the development came from Bernd Gewehr, who presented the problem that was solved with the project. Maybe he can answer this.

Best regards
Thilo



++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Phone:     +49 89 2092 3046
Mobile:    +49 160 756 96 12
E-Mail:     ***@***.***
 
Team Technology GmbH
Karlsplatz 3
80335 München
http://www.teamtechnology.de
 
Sitz der Gesellschaft: München
Amtsgericht München, HRB 206092
Geschäftsführer: Thilo Volprich
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
 
Die E-Mail ist vertraulich. Wenn Sie diese Mail erhalten ohne der richtige Empfänger zu sein, dürfen Sie die Informationen nicht nutzen oder weitergeben. In diesem Fall informieren Sie uns bitte und vernichten diese Mail anschließend.
 
This email is confidential. If you are not the intended recipient, you must not disclose or use the information contained in it. If you have received this mail in error, please tell us immediately by return email and delete the document.

**Comment by BerndGewehr** [comment]
Thanks, @paulswithers, this is deprecated as a project while interesting code.
